import type { Metadata, Viewport } from "next";
// Self-hosted variable fonts (no runtime dependency on Google). Exposed as "Inter Variable" / "JetBrains Mono Variable".
import "@fontsource-variable/inter";
import "@fontsource-variable/jetbrains-mono";
// CJK: split into ~100 unicode-range chunks, browsers fetch only the ones a page needs.
import "@fontsource-variable/noto-sans-sc";
import "./globals.css";
import { AppProviders } from "@/components/providers";
import { AppShell } from "@/components/layout/app-shell";
import { Toaster } from "@/components/ui/sonner";

// Absolute base for og:image / og:url — link previews (Telegram, X DMs, Discord) fetch the picture from here, so it
// must be a domain that is actually served. Boss 9.15: the primary is arm.yyheart.com.
const SITE = process.env.NEXT_PUBLIC_SITE_URL ?? "https://arm.yyheart.com";
const TITLE = "Arm · Community meme launchpad, settled in USDC";
const DESC = "Independent community launchpad on the Arc network (not affiliated with Circle). Free launches, tokens priced in USDC, LP locked forever, creators earn 78% of fees automatically and can share them with promoters.";
// Share card: big picture + "Arm" + arm.yyheart.com wherever the URL is pasted.
const SHARE_TITLE = "Arm — Free meme launches on Arc";
const SHARE_DESC = "Free launches · 78% of fees to creators · referral rewards · arm.yyheart.com";
const SHARE_IMAGE = { url: "/brand/share.jpg", width: 1200, height: 630, alt: SHARE_TITLE };

// Favicon / apple-touch-icon come from src/app/icon.png and src/app/apple-icon.png (generated by scripts/brand-arm.mjs).
export const metadata: Metadata = {
  metadataBase: new URL(SITE),
  title: TITLE,
  description: DESC,
  applicationName: "Arm",
  openGraph: { title: SHARE_TITLE, description: SHARE_DESC, siteName: "Arm", type: "website", url: "/", images: [SHARE_IMAGE] },
  twitter: { card: "summary_large_image", title: SHARE_TITLE, description: SHARE_DESC, site: "@ARKwbe4", images: [SHARE_IMAGE.url] },
};

export const viewport: Viewport = {
  themeColor: "#f4f4f4",
  width: "device-width",
  initialScale: 1,
  // explicitly allow pinch-zoom on mobile browsers (wallet in-app WebViews may still lock it themselves)
  maximumScale: 5,
  userScalable: true,
  viewportFit: "cover",
};

// Runs before paint so the persisted theme never flashes. `?theme=` / `?lang=` override and persist.
// Also sets <html lang> from the stored locale so Edge/Chrome don't auto-translate a Chinese UI they think is
// English, and shields React from translation extensions that rewrap text nodes (boss 9.12: Edge translate made
// the trade panel crash with "insertBefore … not a child of this node" when switching to Sell).
const themeScript = `(function(){try{var q=new URLSearchParams(location.search);var qt=q.get('theme');var ql=q.get('lang');if(qt==='terminal'||qt==='arc'){localStorage.setItem('arm.theme',qt);}if(ql==='zh'||ql==='en'){localStorage.setItem('arm.locale',ql);}var t=localStorage.getItem('arm.theme');if(t==='terminal'||t==='arc'){document.documentElement.dataset.theme=t;}document.documentElement.lang=localStorage.getItem('arm.locale')==='zh'?'zh-CN':'en';}catch(e){}
try{var P=Node.prototype,ib=P.insertBefore,rc=P.removeChild;P.insertBefore=function(n,r){if(r&&r.parentNode!==this){return this.appendChild(n);}return ib.call(this,n,r);};P.removeChild=function(c){if(c&&c.parentNode!==this){return c;}return rc.call(this,c);};}catch(e){}})();`;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // The default theme is light; shadcn's `dark:` variants are bound to data-theme="terminal" in globals.css.
  return (
    <html lang="en" data-theme="arc" className="font-sans" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body className="min-h-full">
        <AppProviders>
          <AppShell>{children}</AppShell>
          <Toaster position="top-center" />
        </AppProviders>
      </body>
    </html>
  );
}
