// Arm brand assets: a monochrome "A / launch arrow" mark + wordmark, rendered to every PNG / JPG the site uses.
//   node scripts/brand-arm.mjs
import sharp from "sharp";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const WEB = join(import.meta.dirname, "..");
const out = (rel) => join(WEB, rel);

/** The mark in a 120×120 box: a bold chevron that reads as an "A" and as an upward launch arrow, with a dot rising
 *  between its legs. `tile` = fill the rounded square behind it. */
function mark({ fg, bg, tile = true, x = 0, y = 0, size = 120 }) {
  const k = size / 120;
  return `<g transform="translate(${x} ${y}) scale(${k})">
    ${tile ? `<rect width="120" height="120" rx="30" fill="${bg}"/>` : ""}
    <path d="M60 18 L100 96 L79 96 L60 58 L41 96 L20 96 Z" fill="${fg}" stroke="${fg}" stroke-width="6" stroke-linejoin="round"/>
    <circle cx="60" cy="84" r="8.5" fill="${fg}"/>
  </g>`;
}

const FONT = "Segoe UI, Arial, sans-serif";
const CJK = "Microsoft YaHei, PingFang SC, sans-serif";
const svg = (w, h, body) => Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">${body}</svg>`);

async function png(rel, w, h, body) {
  await sharp(svg(w, h, body)).png().toFile(out(rel));
  console.log("  ", rel);
}
async function jpg(rel, w, h, body) {
  await sharp(svg(w, h, body)).jpeg({ quality: 90 }).toFile(out(rel));
  console.log("  ", rel);
}

// lock-up (sidebar): mark + "Arm", transparent background; 728×240 = 2× of the 364×120 the layout declares
const lockup = (ink, paper) => `${mark({ fg: paper, bg: ink, size: 200, x: 12, y: 20 })}
  <text x="248" y="178" font-family="${FONT}" font-weight="800" font-size="168" letter-spacing="-6" fill="${ink}">Arm</text>`;
await png("public/brand/logo-arm.png", 728, 240, lockup("#111111", "#ffffff"));
await png("public/brand/logo-arm-dark.png", 728, 240, lockup("#f2f2f2", "#000000"));

// square marks: favicon, apple icon, default token / smoke logo
await png("src/app/icon.png", 512, 512, mark({ fg: "#ffffff", bg: "#111111", size: 512 }));
await png("src/app/apple-icon.png", 180, 180, `<rect width="180" height="180" fill="#111111"/>${mark({ fg: "#ffffff", bg: "#111111", size: 180 })}`);
await png("public/brand/mark.png", 512, 512, mark({ fg: "#ffffff", bg: "#111111", size: 512 }));
await png("public/brand/logo.png", 512, 512, mark({ fg: "#ffffff", bg: "#111111", size: 512 }));
await png("public/brand/logo-navy.png", 512, 512, mark({ fg: "#111111", bg: "#ffffff", size: 512 }));

// share card 1200×630 (X / Telegram / OG preview)
const share = `<rect width="1200" height="630" fill="#000000"/>
  <rect x="0" y="0" width="1200" height="630" fill="url(#g)"/>
  <defs><radialGradient id="g" cx="0.78" cy="0.2" r="0.8"><stop offset="0" stop-color="#2a2a2a"/><stop offset="1" stop-color="#000000"/></radialGradient></defs>
  ${mark({ fg: "#000000", bg: "#ffffff", size: 190, x: 90, y: 120 })}
  <text x="320" y="270" font-family="${FONT}" font-weight="800" font-size="160" letter-spacing="-6" fill="#ffffff">Arm</text>
  <text x="92" y="410" font-family="${CJK}" font-weight="700" font-size="54" fill="#ffffff">免费发币 · 78% 手续费归创作者 · 推广分佣</text>
  <text x="92" y="478" font-family="${FONT}" font-weight="500" font-size="34" fill="#a6a6a6">Free launches · 78% of fees to creators · Referral rewards · USDC on Arc</text>
  <line x1="92" y1="540" x2="1108" y2="540" stroke="#333333" stroke-width="2"/>
  <text x="92" y="590" font-family="${FONT}" font-weight="600" font-size="28" letter-spacing="4" fill="#737373">BUILT ON ARC</text>
  <text x="1108" y="590" text-anchor="end" font-family="${FONT}" font-weight="600" font-size="30" fill="#f2f2f2">arm.yyheart.com</text>`;
await jpg("public/brand/share.jpg", 1200, 630, share);
await png("public/brand/og.png", 1200, 630, share);

// home hero banner 1600×506
const hero = `<rect width="1600" height="506" fill="#000000"/>
  <defs><radialGradient id="h" cx="0.85" cy="0.1" r="0.9"><stop offset="0" stop-color="#262626"/><stop offset="1" stop-color="#000000"/></radialGradient></defs>
  <rect width="1600" height="506" fill="url(#h)"/>
  ${mark({ fg: "#ffffff", bg: "#000000", tile: false, size: 520, x: 1060, y: -20 })}
  <text x="96" y="200" font-family="${FONT}" font-weight="800" font-size="150" letter-spacing="-6" fill="#ffffff">Arm</text>
  <text x="100" y="298" font-family="${CJK}" font-weight="700" font-size="58" fill="#ffffff">免费发币，手续费 78% 归你</text>
  <text x="100" y="368" font-family="${CJK}" font-weight="400" font-size="36" fill="#a6a6a6">开启推广分佣，让别人帮你带量 · USDC 计价 · LP 永久锁定</text>
  <text x="100" y="440" font-family="${FONT}" font-weight="600" font-size="28" letter-spacing="4" fill="#737373">MEME LAUNCHPAD ON ARC</text>`;
await jpg("public/brand/hero.jpg", 1600, 506, hero);

writeFileSync(out("public/brand/README.txt"), "Generated by scripts/brand-arm.mjs — edit the script, not the images.\n");
console.log("done");
